pennies = int(input("How many pennies do you have? "))
nickels = int(input("How many nickels do you have? "))
dimes = int(input("How many dimes do you have? "))
quarters = int(input("How many quarters do you have? "))
halfDollars = int(input("How many halfDollars do you have? "))
oneDollars = int(input("How many oneDollars do you have? "))
print("You have " + str(pennies) + " pennies.")
print("You have " + str(nickels) + " nickels.")
print("You have " + str(dimes) + " dimes.")
print("You have " + str(quarters) + " quarters.")
print("You have " + str(halfDollars) + " halfDollars.")
print("You have " + str(oneDollars) + " oneDollars.")
total = pennies + (5 * nickels) + (10 * dimes) + (25 * quarters) + (50 * halfDollars) + (100 * oneDollars)
print ("The value of all your coins is $" + str(total/100) + ".")